POST http://localhost:3003/client/simulation
Content-Type: application/json

{
     "cpf": "798.798.798-70",
     "uf": "MG",
     "birthData": "31/07/2002",
     "loanAmount": 60000,
     "amountPerMonth": 15000
}

###

POST http://localhost:3003/client/insertinbank
Content-Type: application/json

{
     "cpf": "798.798.798-71",
     "rate": 0.01,
     "birthData": "31/07/2002",
     "loanAmount": 60000,
     "amountPerMonth": 15000
}
###

GET  http://localhost:3003/client/select
Content-Type: application/json